[package]
name = "gltf_unlit_generator"
version = "0.1.0"
authors = ["Robert Long <rlong@mozilla.com>"]

[dependencies]
image = "0.18.0"
clap = "2.31.2"

[dependencies.gltf]
version = "0.10.1"
features = ["extras", "names"]
